<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streaming.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streamingStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/episode/episode.css">
<div class="background"></div>
<header class="header-main">
  <h1 class="title title-main" style="text-align:center;">Streaming World</h1>
  <div class="ban-top">
    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav menu__list">
        <li class="active menu__item menu__item--current"><a class="menu__link" href="<?= $requestUrl ?>/">Home</a></li>
        <li class="dropdown menu__item">
          <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Artworks <span class="caret"></span></a>
          <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <?php foreach ($artworks as $artwork): ?>
                    <li><a href="<?= $requestUrl ?>/oeuvres/<?= $artwork['Url'] ?>"><?= $artwork['Name'] ?></a></li>
                  <?php endforeach; ?>
                </ul>
                <div class="clearfix"></div>
              </div>
            </ul>
          </li>
          <li class="dropdown menu__item">
            <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
            <ul class="dropdown-menu multi-column columns-3">
              <div class="row">
                <div class="col-sm-3 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <li><a href="<?= $requestUrl ?>/products">Tous nos produits</a></li>
                  </ul>
                </div>
                <div class="col-sm-3 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <?php foreach ($lines as $line) {?>
                      <li>
                        <a href="<?= $requestUrl ?>/products/product?name=<?=$line['ProductLine']?>"><?= ucfirst($line['ProductLine']) ?></a>
                        </li>
                      <?php } ?>
                  </ul>
                <div class="clearfix"></div>
              </div>
            </div>
            </ul>
          </li>
          <li class="dropdown menu__item">
            <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Streaming <span class="caret"></span></a>
            <ul class="dropdown-menu multi-column columns-3">
              <div class="row">
                <div class="col-sm-3 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <li><a href="<?= $requestUrl ?>/streaming">Tous nos streamings</a></li>
                  </ul>
                </div>
                <div class="col-sm-3 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <?php foreach ($artworks as $artwork): ?>
                      <li><a href="<?= $requestUrl ?>/streaming/artwork?name=<?= $artwork['Url'] ?>"><?= $artwork['Name'] ?></a></li>
                    <?php endforeach; ?>
                  </ul>
                </div>
                <div class="clearfix"></div>
              </div>
            </ul>
          </li>
          <?php if (array_key_exists('role', $_SESSION) === false){ ?>
            <li class=" menu__item"><a class="dropdown-toggle menu__link" href="<?= $requestUrl ?>/users/login">Login</a></li>
          <?php }else{ ?>
            <li class="dropdown menu__item">
              <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="far fa-user-circle" style="font-size: 0.9rem; color:white"></i> <span class="caret"></span></a>
              <ul class="dropdown-menu multi-column columns-3">
                <div class="row">
                  <div class="col-sm-3 multi-gd-img">
                    <ul class="multi-column-dropdown">
                      <?php if ($_SESSION['role'] === 'admin'){ ?>
                        <li><a href="<?= $requestUrl ?>/users/admin">Admin</a></li>
                      <?php } ?>
                      <li><a href="<?= $requestUrl ?>/users/profil">Profil</a></li>
                      <li><a href="<?= $requestUrl ?>/users/logout">Logout</a></li>
                    </ul>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </ul>
            </li>
          <?php } ?>
        </ul>
      </div>
      <div class="top_nav_right">
        <div class="cart box_1">
          <a href="<?= $requestUrl ?>/basket">
            <h3> <div class="total">
              <i class="fas fa-shopping-cart" aria-hidden="true"></i>
              <span class="simpleCart_total"></span> (<span id="itemBasket" class="simpleCart_quantity"></span> item(s))</div>
            </h3>
          </a>
          <p><a href="javascript:;" class="empty">Vider votre panier</a></p>

        </div>
      </div>
    </div>
    <aside class="episode-list">
      <ul>
        <?php foreach ($episodes as $episode): ?>
          <li><a href="<?= $requestUrl ?>/streaming/artwork/episode?artworkId=<?= $episode['ArtworkId'] ?>&status=<?= $episode['Status']?>"><?= $episode['Caption'] ?></a></li>
        <?php endforeach; ?>
      </ul>
    </aside>
    <main class="container">
      <div class="content">
        <div class="episode">
          <?php if ($status - 1 === 0){ ?>

          <?php }else{ ?>
            <a href="<?= $requestUrl ?>/streaming/artwork/episode?artworkId=<?= $streamings['ArtworkId'] ?>&status=<?= $status-1?>"><i class="far fa-arrow-alt-circle-left"></i> Episode précédent</a>
          <?php } ?>
          <h2 class="title-vid"><?= $streamings['Caption'] ?></h2>
          <?php if (($status + 1) > count($episodes)){ ?>

          <?php }else{ ?>
            <a href="<?= $requestUrl ?>/streaming/artwork/episode?artworkId=<?= $streamings['ArtworkId'] ?>&status=<?= $status+1?>">Episode suivant <i class="far fa-arrow-alt-circle-right"></i></a>
          <?php } ?>
        </div>
        <video src="../../../../streaming_vids/<?= $streamings['Video']?> " controls width="854"  height="480" controlsList="nodownload" poster="<?= $wwwUrl ?>/ressources/images/cover/<?= $streamings['Image_Cover'] ?>">
        </video>
      </div>
      <section class="espace-com">
        <h4>Espace commentaire</h4>
        <div class="show-post">
          <?php for($i = 0; $i < count($posts); $i++){ ?>
            <div class="post">
              <h5 class="title-post"><?= $posts[$i]['Nickname'] ?></h5>
              <p><?= $posts[$i]['Content'] ?></p>
              <p><em><?= $posts[$i]['CreationTimestamp'] ?></em></p>
              <div class="show-com">
                <?php foreach ($comments as $comment): ?>
                  <h6 class="title-comment"><?= $comment['Nickname'] ?></h6>
                  <p><?= $comment['Content'] ?></p>
                  <p><em><?= $comment['CreationTimestamp'] ?></em></p>
                <?php endforeach; ?>
              </div>
              <p class="add-comment" data-id="<?= $i ?>">Répondre</p>
              <form class="form-com" action="<?= $requestUrl ?>/streaming/artwork/episode?artworkId=<?= $streamings['ArtworkId'] ?>&status=<?= $streamings['Status'] ?>" method="post">
                <textarea name="com" rows="1" cols="40" placeholder="Répondre"></textarea>
                <input type="hidden" name="postId" value="<?= $posts[$i]['Id'] ?>">
                <input type="submit" name="envoyer" value="Envoyer">
              </form>
            </div>
          <?php } ?>
        </div>
        <form class="form-post" action="<?= $requestUrl ?>/streaming/artwork/episode?artworkId=<?= $streamings['ArtworkId'] ?>&status=<?= $streamings['Status'] ?>" method="post">
          <textarea name="post" rows="4" cols="80" placeholder="Ecrire un nouveau commentaire"></textarea>
          <input type="hidden" name="episodeId" value="<?= $streamings['Id'] ?>">
          <input type="submit" name="envoyer" value="Envoyer">
        </form>
      </section>
    </main>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/episode.js"></script>
