<link rel="stylesheet" href="<?= $wwwUrl ?>/css/persos.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/inosuke.css">

<section class="section-main background">
  <h2 class="title-second">Background</h2>
  <p>Il est également un pourfendeur de démons et un compagnon de voyage de Tanjirō qui porte un masque de sanglier. Il a vécu la majeure partie de sa vie dans les bois, élevé par un sanglier, où il s'est battu avec des bêtes et des démons. C'un épéiste qualifié qui utilise deux lames pour se battre et un style personnel, nommé le « souffle de la Bête » (獣の呼吸法, Kemono no kokyū-hō). Il est culotté et enclin à réagir violemment, bien qu'il ne paraisse pas très futé, il a fait ses preuves maintes fois au combat. Il est extrêmement musclé et robuste, ce qui contraste avec son visage étrangement efféminé, qu'il cache normalement sous son masque. Lorsqu'il rencontre Tanjirō pour la première fois, il le considère comme un ennemi, mais il devient rapidement un ami lorsqu'ils se battent. Il défie souvent Tanjirō à des compétitions acceptées avec bonne humeur. Il a passé le test en même temps que Tanjirō et Zenitsu et a apparemment été le premier à le terminer. Ses katanas sont gris-violet.</p>
</section>
<section class="section-main caractere">
  <h2 class="title-second">Caractere</h2>
  <p>Inosuke est extraordinairement coléreux et fier. Il fait beaucoup pour combattre des adversaires plus forts que lui, affirmant que c'est son seul passe-temps. Inosuke ne pensera pas à la différence de pouvoir entre lui et son adversaire; cela l'a souvent amené à être en danger. Il essaie toujours de rivaliser avec Tanjiro et de l'inciter à se battre avec lui et échoue généralement.<p>
  <div class="second-container">
    <figure>
      <img alt="cara1" src="<?= $wwwUrl ?>/ressources/images/persos/cara_ino_1.png">
      <figcaption>Colérique</figcaption>
    </figure>
    <figure>
      <img alt="cara2" src="<?= $wwwUrl ?>/ressources/images/persos/cara_ino_2.png">
      <figcaption>Admiratif</figcaption>
    </figure>
    <figure>
      <img alt="cara6" src="<?= $wwwUrl ?>/ressources/images/persos/cara_ino_6.png">
      <figcaption>Vantard</figcaption>
    </figure>
    <figure>
      <img alt="cara5" src="<?= $wwwUrl ?>/ressources/images/persos/cara_ino_5.png">
      <figcaption>Prise de conscience</figcaption>
    </figure>
    <figure>
      <img alt="cara4" src="<?= $wwwUrl ?>/ressources/images/persos/cara_ino_4.png">
      <figcaption>Son vrai visage</figcaption>
    </figure>
  </div>
  <p>Ayant grandi seul dans les montagnes, Inosuke a du mal à interagir avec les autres et ne se soucie que de lui-même la plupart du temps. Cependant, au fil du temps, Inosuke est de plus en plus influencé par Tanjiro. Il commence également à réfléchir et à utiliser des stratégies avant de se lancer de front avec un adversaire.</p>
</section>
<section class="section-main capacity">
  <h2 class="title-second">Capacites</h2>
  <article class="article-main natural">
    <h3 class="title-third">Capacités Naturelles </h3>
    <figure>
      <img alt="cara3" src="<?= $wwwUrl ?>/ressources/images/persos/cara_ino_3.png">
      <figcaption>Souplesse</figcaption>
    </figure>
    <p><span class="capa">Sens du toucher amélioré:</span> Après avoir grandi dans les montagnes, Inosuke a développé un sens aigu du toucher. Il peut même sentir de petites vibrations dans l'air.</p>
    <p><span class="capa">Souplesse:</span> Inosuke a un sens extrêmement fort de la flexibilité, au point qu'il est capable de disloquer n'importe quelle articulation de son corps par sa propre volonté.</p>
  </article>
  <article class="article-main style">
    <h3 class="title-third">Style</h3>
    <p><span class="capa">Souffle de la bête (獣の呼吸 Kedamono no kokyū):</span> Développé par Inosuke après avoir vécu dans les montagnes. Avec son sens du toucher amélioré, il peut utiliser plusieurs techniques différentes.</p>
    <p><span class="gras">Premier croc:</span> Percer et Extraire (壱ノ牙 穿ち抜き Ichi no kiba: Ugachi nuki)- Inosuke poignarde le cou de la cible avec les deux lames.</p>
    <figure>
      <img alt="souffle1" src="<?= $wwwUrl ?>/ressources/images/persos/croc1.png">
      <figcaption>1er mouvement</figcaption>
    </figure>
    <p><span class="gras">Troisième croc:</span> Déchirer et dévorer (参ノ牙 喰い裂き San no kiba: Kuizaki)- Coups horizontaux simultanés vers la gorge de la cible.</p>
    <figure>
      <img alt="souffle3" src="<?= $wwwUrl ?>/ressources/images/persos/croc3.gif">
      <figcaption>3ème mouvement</figcaption>
    </figure>
    <p><span class="gras">Septième Croc:</span> Conscience spatiale  (漆ノ牙 空間識覚 Shichi no kiba: Kūkanshiki kaku)- Inosuke peut identifier la position des ennemis en ressentant de petites perturbations dans l'air. Il plonge généralement ses deux lames Nichirin dans le sol pour utiliser cette technique.</p>
    <figure>
      <img alt="souffle7" src="<?= $wwwUrl ?>/ressources/images/persos/croc7.gif">
      <figcaption>7ème mouvement</figcaption>
    </figure>
  </article>
</section>
