<link rel="stylesheet" href="<?= $wwwUrl ?>/css/persos.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/nezuko.css">

<section class="section-main background">
	<h2 class="title-second">Background</h2>
	<p>La fille aînée d'un vendeur de charbon de bois et l'une des petites sœurs de Tanjirō. Elle est la seule survivante de leur famille après l'attaque d'un démon, cependant, elle a été transformée en une démon. Néanmoins, elle conserve ses souvenirs et les sentiments envers son frère qui la retient de ses impulsions de démon. Devenue sensible à la lumière du soleil, elle est transportée dans un caisson en bois par son frère lors de leurs voyages. L'hypnose par la suite d'Urokodaki l'a aidée à se transformer en une démon qui ne consomme pas de chair humaine. Elle récupère de l'énergie en dormant et ne fait que du mal aux démons mauvais. Elle est incapable de parler en tant que démon, mais elle doit également porter un bâillon en bambou afin d'éviter de mordre qui que ce soit. Elle possède plusieurs pouvoirs, dont la régénération, la force surhumaine, grandir et rétrécir rapidement et une technique qui brûle le sang qui se trouve en dehors de son corps.</p>
</section>
<section  class="section-main caractere">
	<h2 class="title-second">Caractère</h2>
	<p>La personnalité originelle de Nezuko en tant qu'humaine était celle d'une fille gentille et bienveillante, qui pensait aux autres avant elle-même, tout comme son frère aîné Tanjiro. Elle était une sœur aînée responsable de ses frères et sœurs plus jeunes. <br/>
	En tant que démon, Nezuko semble avoir oublié une bonne partie de ses souvenirs en tant qu'humaine, outre ceux liés à sa famille. Elle est toujours très attentionnée et protectrice envers les autres humains qu'elle considère comme des membres de sa famille en raison de l'influence d'Urokodaki alors qu'elle était endormie pendant deux ans. Elle est aussi assez effrontée et ne semble pas craindre de se battre; elle garde férocement son frère ainsi que ses alliés.</p>
	<div class="second-container">
		<figure>
			<img alt="cara1" src="<?= $wwwUrl ?>/ressources/images/persos/cara1.jpg">
			<figcaption>kawaii</figcaption>
		</figure>
		<figure>
			<img alt="cara2" src="<?= $wwwUrl ?>/ressources/images/persos/cara_nezu_2.png">
			<figcaption>effrontée</figcaption>
		</figure>
		<figure>
			<img alt="cara3" src="<?= $wwwUrl ?>/ressources/images/persos/cara3.jpg">
			<figcaption>soucieuse</figcaption>
		</figure>
		<figure>
			<img alt="cara4" src="<?= $wwwUrl ?>/ressources/images/persos/cara_nezu_4.png">
			<figcaption>protectrice</figcaption>
		</figure>
		<figure>
			<img alt="cara5" src="<?= $wwwUrl ?>/ressources/images/persos/cara_nezu_5.png">
			<figcaption>protectrice</figcaption>
		</figure>
	</div>
	<p>Elle a également développé une forte volonté en refusant de consommer de la chair ou du sang humain, même en cas de blessure extrême ou d'exposition au sang humain, telle que le sang Marechi de Sanemi Shinazugawa. Elle conserve toujours ses émotions humaines, comme on l'a vue pleurer et être heureuse, mais en général, elle semble plus détachée que ses cohortes humaines, ainsi que plus calme et moins malveillante que la plupart des démons. En tant que démon, Nezuko ne parle pas souvent et bégaie beaucoup. Cela peut être dû à son embout en bambou, qui est rarement retiré. Cela signifie aussi qu'elle est parfois difficile à lire.</p>
</section>
<section class="section-main capacity">
	<h2 class="title-second">Capacités</h2>
	<article class="article-main natural">
		<h3 class="title-third">CAPACITES DEMONIAQUES </h3>
		<figure>
			<img alt="taille" src="<?= $wwwUrl ?>/ressources/images/persos/capa2.gif">
			<figcaption>taille</figcaption>
		</figure>
		<p><span class="gras">Manipulation de la taille:</span> Après avoir été transformée en démon, Nezuko a démontré sa capacité de base pour changer et modifier la taille et la taille de son corps. Elle était capable de se réduire à la taille physique d'un petit enfant afin de se glisser dans une boîte ou un panier afin de se protéger du soleil lors de ses déplacements dans la journée avec Tanjiro. Elle pouvait également prendre une forme beaucoup plus grande pour se capable de lutter contre les démons.</p>
		<p><span class="gras">Force accrue:</span> Bien que n'ayant jamais été formellement formée, la force physique naturellement améliorée de Nezuko lui permet de lutter facilement contre les démons. En raison de son manque d'entraînement, Nezuko s'appuie plutôt sur le simple fait de donner des coups de pied à ses adversaires ou de les écraser avec une force brutale. Son pouvoir de frappe dépend de la taille de son corps, et ses battements permettent également de couper facilement la tête des démons.</p>
		<div class="mvts">
			<div class="mvt">
				<figure>
					<img alt="strong" src="<?= $wwwUrl ?>/ressources/images/persos/capa3.gif">
					<figcaption>strong</figcaption>
				</figure>
			</div>
			<div class="mvt">
				<figure>
					<img alt="strong" src="<?= $wwwUrl ?>/ressources/images/persos/capa4.gif">
					<figcaption>strong</figcaption>
				</figure>
			</div>
		</div>
		<p><span class="gras">Régénération:</span> Nezuko possède une formidable capacité de régénération capable de restaurer les membres coupés en quelques secondes. La vraie nature de cette capacité est la solidification de son sang à partir de parties de son corps qu'elle pourrait manipuler à volonté.</p>
	</article>
	<article class="article-main style">
		<h3 class="title-third">TECHNIQUE DU DEMON DE SANG (鬼 術 KEKKIJUTSU)</h3>
		<p><span class="gras">Rafale de sang (血 血 Bakketsu):</span> Nezuko fait instantanément flamber son sang avec des flammes chaudes. Nezuko pouvait contrôler la température de ses flammes de manière non létale (comme indiqué lorsqu’elle réveille de force Tanjiro lors de l’incident du train démon) ou mortelle à volonté. Les flammes de Nezuko sont également capables de transformer la lame Nichirin de Tanjiro du noir jais au rouge cramoisi, renforçant encore la lame et permettant à Tanjiro d'interpréter plus efficacement les styles de danse du feu.</p>
		<figure>
			<img alt="blood demon technique" src="<?= $wwwUrl ?>/ressources/images/persos/capa.gif">
			<figcaption>technique du démon de sang</figcaption>
		</figure>
	</article>
</section>
