<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Streaming World</title>
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
  <script type="text/javascript" src="<?= $wwwUrl ?>/js/jquery-2.1.4.min.js"></script>
  <script type="text/javascript" src="<?= $wwwUrl ?>/js/bootstrap-3.1.1.min.js"></script>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <!-- Feuilles de styles de l'application -->

  <!-- Librairie jQuery -->
  <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

  <!-- JavaScript de l'application -->
  <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body id='haut'>

  <?php include $this->viewData['template']; ?>
  <footer class="footer-main" style="text-align:center; padding-top: 90px;">
    <small style="color: white; font-style: italic;">Copyright (c) 2020 Copyright Holder All Rights Reserved.</small>
    <div id="up">
      <a href="#top">
        <img alt="toplogo" class="top-logo" src="<?= $wwwUrl ?>/ressources/images/top/top.gif"/>
      </a>
    </div>
  </footer>
  <script type="text/javascript" src='<?= $wwwUrl ?>/js/kimetsu.js'></script>
</body>
</html>
