<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<header class="header-main">
  <h1 class="title title-main" style="text-align:center;">Streaming World</h1>
  <div class="ban-top">
    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav menu__list">
        <li class="active menu__item menu__item--current"><a class="menu__link" href="/streaming-world/index.php/">Home</a></li>
        <li class="dropdown menu__item">
          <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Artworks <span class="caret"></span></a>
          <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <li><a href="/streaming-world/index.php/oeuvres/kny">Kimetsu No Yaiba</a></li>
                  <li><a href="#">Vinland Saga</a></li>
                  <li><a href="#">Dragon Ball</a></li>
                  <li><a href="#">Naruto</a></li>
                  <li><a href="#">One Piece</a></li>
                  <li><a href="#">Bleach</a></li>
                  <li><a href="#">Gintama</a></li>
                </ul>
              </div>
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <li><a href="#">The Walking Dead</a></li>
                  <li><a href="#">La Casa De Papel</a></li>
                  <li><a href="#">Breaking Bad</a></li>
                  <li><a href="#">Fast &amp; Furious</a></li>
                  <li><a href="#">Spider Man</a></li>
                  <li><a href="#">Avenger</a></li>
                  <li><a href="#">Bollywood</a></li>
                </ul>
              </div>
              <div class="clearfix"></div>
            </div>
          </ul>
        </li>
        <li class="dropdown menu__item">
          <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <li><a href="womens.html">Tous nos produits</a></li>
                  <li><a href="womens.html">Figurines</a></li>
                  <li><a href="womens.html">Tomes</a></li>
                  <li><a href="womens.html">Blu-ray</a></li>
                  <li><a href="womens.html">Accessoires</a></li>
                </ul>
              </div>
              <div class="clearfix"></div>
            </div>
          </ul>
        </li>
        <li class="dropdown menu__item">
          <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Streaming <span class="caret"></span></a>
          <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <li><a href="/streaming-world/index.php/oeuvres/kny">Kimetsu No Yaiba</a></li>
                  <li><a href="#">Vinland Saga</a></li>
                  <li><a href="#">Dragon Ball</a></li>
                  <li><a href="#">Naruto</a></li>
                  <li><a href="#">One Piece</a></li>
                  <li><a href="#">Bleach</a></li>
                  <li><a href="#">Gintama</a></li>
                </ul>
              </div>
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <li><a href="#">The Walking Dead</a></li>
                  <li><a href="#">La Casa De Papel</a></li>
                  <li><a href="#">Breaking Bad</a></li>
                  <li><a href="#">Fast &amp; Furious</a></li>
                  <li><a href="#">Spider Man</a></li>
                  <li><a href="#">Avenger</a></li>
                  <li><a href="#">Bollywood</a></li>
                </ul>
              </div>
              <div class="clearfix"></div>
            </div>
          </ul>
        </li>
                  <li class=" menu__item"><a class="dropdown-toggle menu__link" href="/streaming-world/index.php/users/login">Login</a></li>
                <li class=" menu__item"><a class="menu__link" href="contact.html">contact</a></li>
      </ul>
    </div>
    <div class="top_nav_right">
      <div class="cart box_1">
        <a href="checkout.html">
          <h3> <div class="total">
            <i class="fas fa-shopping-cart" aria-hidden="true"></i>
            <span class="simpleCart_total"></span> (<span id="simpleCart_quantity" class="simpleCart_quantity"></span> items)</div>

          </h3>
        </a>
        <p><a href="javascript:;" class="simpleCart_empty">Empty Cart</a></p>

      </div>
    </div>
  </div>
</header>
<main class="container">

<div class="login-right">
  <h3>Connectez-vous !</h3>
  <form class="b-form" action="login" method="POST">
    <div class="sign-in">
      <h4>Email :</h4>
      <input type="text" name="email" placeholder="email">
    </div>
    <div class="sign-in">
      <h4>Password :</h4>
      <input type="password" name="password" placeholder="password">
      <a href="#">Forgot password?</a>
    </div>
    <div class="sign-in">
      <input type="submit" value="Connexion">
      <p>Vous n'avez pas encore de compte ? Enregistrez-vous <a href="<?= $requestUrl ?>/users/register">ici !</a></p>
    </div>
  </form>
</div>
</main>
