<?php if ($error != null) { ?>
  <small style="color: red; margin-left:300px; font-style: italic;"><?= $error ?></small>
<?php } ?>

<div>
  <h3>Connectez-vous !</h3>
  <form class="b-form" action="login" method="POST">
    <input type="text" name="email" placeholder="email">
    <input type="password" name="password" placeholder="password">
    <input type="submit" value="Connexion">
  </form>
</div>

<p>Vous n'avez pas encore de compte ? Enregistrez-vous <a href="<?= $requestUrl ?>/users/register">ici !</a></p>
