<?php if ($error != null) {?>
  <p><?= $error ?></p>
<?php } ?>
<div>
	<h3>Enregistrez vous !</h3>
	<form class="b-form" action="Register" method="POST">
		<input type="text" name="firstname" placeholder="Prénom">
		<input type="text" name="lastname" placeholder="Nom">
    <input type="text" name="pseudo" placeholder="Pseudo">
		<input type="text" name="email" placeholder="Email">
		<input type="password" name="password" placeholder="Mot de passe">
		<input type="text" name="address" placeholder="Adresse">
		<input type="text" name="city" placeholder="Ville">
		<input type="text" name="zip" placeholder="Code postal">
		<input type="submit" value="Enregister">
	</form>
</div>
