<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/products/products.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/products/detail/detail.css">

<header class="header-main">
  <h1 class="title title-main" style="text-align:center;">Streaming World</h1>
  <div class="ban-top">
    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav menu__list">
        <li class="active menu__item menu__item--current"><a class="menu__link" href="<?= $requestUrl ?>/">Home</a></li>
        <li class="dropdown menu__item">
          <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Artworks <span class="caret"></span></a>
          <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <?php foreach ($artworks as $artwork): ?>
                    <li><a href="<?= $requestUrl ?>/oeuvres/<?= $artwork['Url'] ?>"><?= $artwork['Name'] ?></a></li>
                  <?php endforeach; ?>
                </ul>
              <div class="clearfix"></div>
            </div>
          </ul>
        </li>
        <li class="dropdown menu__item">
          <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <li><a href="<?= $requestUrl ?>/products">Tous nos produits</a></li>
                </ul>
              </div>
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <?php foreach ($lines as $line) {?>
                    <li>
                      <a href="<?= $requestUrl ?>/products/product?name=<?=$line['ProductLine']?>"><?= ucfirst($line['ProductLine']) ?></a>
                      </li>
                    <?php } ?>
                </ul>
              <div class="clearfix"></div>
            </div>
          </div>
          </ul>
        </li>
        <li class="dropdown menu__item">
          <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Streaming <span class="caret"></span></a>
          <ul class="dropdown-menu multi-column columns-3">
            <div class="row">
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <li><a href="<?= $requestUrl ?>/streaming">Tous nos streamings</a></li>
                </ul>
              </div>
              <div class="col-sm-3 multi-gd-img">
                <ul class="multi-column-dropdown">
                  <?php foreach ($artworks as $artwork): ?>
                    <li><a href="<?= $requestUrl ?>/streaming/artwork?name=<?= $artwork['Url'] ?>"><?= $artwork['Name'] ?></a></li>
                  <?php endforeach; ?>
                </ul>
              </div>
              <div class="clearfix"></div>
            </div>
          </ul>
        </li>
        <?php if (array_key_exists('role', $_SESSION) === false){ ?>
          <li class=" menu__item"><a class="dropdown-toggle menu__link" href="<?= $requestUrl ?>/users/login">Login</a></li>
        <?php }else{ ?>
          <li class="dropdown menu__item">
            <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="far fa-user-circle" style="font-size: 0.9rem; color:white"></i> <span class="caret"></span></a>
            <ul class="dropdown-menu multi-column columns-3">
              <div class="row">
                <div class="col-sm-3 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <?php if ($_SESSION['role'] === 'admin'){ ?>
                      <li><a href="<?= $requestUrl ?>/users/admin">Admin</a></li>
                    <?php } ?>
                    <li><a href="<?= $requestUrl ?>/users/profil">Profil</a></li>
                    <li><a href="<?= $requestUrl ?>/users/logout">Logout</a></li>
                  </ul>
                </div>
                <div class="clearfix"></div>
              </div>
            </ul>
          </li>
        <?php } ?>
      </ul>
    </div>
    <div class="top_nav_right">
      <div class="cart box_1">
        <a href="<?= $requestUrl ?>/basket">
          <h3> <div class="total">
            <i class="fas fa-shopping-cart" aria-hidden="true"></i>
            <span class="simpleCart_total"></span> (<span id="itemBasket" class="simpleCart_quantity"></span> item(s))</div>
          </h3>
        </a>
        <p><a href="javascript:;" class="empty">Vider votre panier</a></p>

      </div>
    </div>
  </div>
</div>
</header>
<main class="container">
  <a class="comeBack" href="<?= $requestUrl ?>/products"><i class="fas fa-arrow-circle-left"></i></a>
  <div class="productDetail">
    <img src="<?= $wwwUrl?>/ressources/images/products/<?=$product['Photo']?>">
    <h3><?=$product['Name']?></h3>
    <p><?=$product['Description']?></p>
    <div class="paymentPart">
      <span>Prix Unitaire : <em><?=$product['Price']?> €</em></span>
      <form>
        <input type="text" name="quantity" id="product-<?=$product['Id']?>">
        <button class="addToBasket" data-name="<?=$product['Name']?>" data-price="<?=$product['Price']?>" data-id="<?=$product['Id']?>"><p>Ajouter au panier</p></button>
      </form>
    </div>
  </div>
</main>
